title: Odessa Lohika's Java Club
email: apletnev@lohika.com
description: >- # this means to ignore newlines until "baseurl:"
    Let's brew some java
baseurl: "" # the subpath of your site, e.g. /blog
repository: odessajavaclub/odessajavaclub.github.io
url: "https://odessajavaclub.github.io" # the base hostname & protocol for your site, e.g. http://example.com
show_downloads: "false"

# excerpts
show_excerpts: "true"
excerpt_separator: <!--more-->

# google_analytics: [Your Google Analytics tracking ID]

paginate: 5

# Build settings
markdown: kramdown
theme: jekyll-theme-modernist
plugins:
    - jekyll-feed
    - jekyll-paginate
